//
//  DevToolsCatalogPart1.swift
//  CodeEdit
//
//

import Foundation

/// Catalog partition 1: Tools for Categories 1 through 4 (64 Tools).
public struct DevToolsCatalogPart1: Sendable {
    public static let tools: [DevToolItem] = [
        // Category 1: Code & Schema Generators (15 Tools)
        DevToolItem(id: "json_to_swift", title: "JSON to Swift", category: .codeGenerators,
                    summary: "Generates Swift Codable structs.", iconName: "swift"),
        DevToolItem(id: "json_to_ts", title: "JSON to TypeScript", category: .codeGenerators,
                    summary: "Generates TypeScript interfaces.", iconName: "curlybraces"),
        DevToolItem(id: "json_to_python", title: "JSON to Python", category: .codeGenerators,
                    summary: "Generates Python Pydantic models.", iconName: "curlybraces"),
        DevToolItem(id: "json_to_go", title: "JSON to Go Structs", category: .codeGenerators,
                    summary: "Generates Go struct definitions.", iconName: "curlybraces"),
        DevToolItem(id: "json_to_rust", title: "JSON to Rust Serde", category: .codeGenerators,
                    summary: "Generates Rust structs with Serde.", iconName: "gearshape.2"),
        DevToolItem(id: "json_to_kotlin", title: "JSON to Kotlin", category: .codeGenerators,
                    summary: "Generates Kotlin data classes.", iconName: "k.circle"),
        DevToolItem(id: "json_to_java", title: "JSON to Java POJO", category: .codeGenerators,
                    summary: "Generates Java POJO classes.", iconName: "j.circle"),
        DevToolItem(id: "json_to_csharp", title: "JSON to C# Record", category: .codeGenerators,
                    summary: "Generates C# record classes.", iconName: "number.circle"),
        DevToolItem(id: "json_to_dart", title: "JSON to Dart", category: .codeGenerators,
                    summary: "Generates Dart classes for Flutter.", iconName: "d.circle"),
        DevToolItem(id: "json_to_php", title: "JSON to PHP", category: .codeGenerators,
                    summary: "Generates PHP 8 typed classes.", iconName: "p.circle"),
        DevToolItem(id: "json_schema_generator", title: "JSON Schema Gen", category: .codeGenerators,
                    summary: "JSON to Draft-07 JSON Schema.", iconName: "doc.text"),
        DevToolItem(id: "json_type_analyzer", title: "JSON Type Analyzer", category: .codeGenerators,
                    summary: "Inspects field types and nulls.", iconName: "magnifyingglass"),
        DevToolItem(id: "json_to_csv", title: "JSON to CSV", category: .codeGenerators,
                    summary: "Flattens JSON arrays to CSV.", iconName: "tablecells"),
        DevToolItem(id: "json_to_toml", title: "JSON to TOML", category: .codeGenerators,
                    summary: "Converts JSON to TOML format.", iconName: "doc.badge.gearshape"),
        DevToolItem(id: "qr_code_generator", title: "QR Code Generator", category: .codeGenerators,
                    summary: "Generates QR codes from text.", iconName: "qrcode"),

        // Category 2: Format Converters & Parsers (18 Tools)
        DevToolItem(id: "yaml_to_json", title: "YAML to JSON", category: .formatConverters,
                    summary: "Parses YAML to JSON.", iconName: "arrow.left.arrow.right"),
        DevToolItem(id: "json_formatter", title: "JSON Formatter", category: .formatConverters,
                    summary: "Pretty-prints or minifies JSON.", iconName: "text.alignleft"),
        DevToolItem(id: "yaml_converter", title: "YAML / JSON Converter", category: .formatConverters,
                    summary: "Bidirectional YAML and JSON.", iconName: "arrow.left.arrow.right"),
        DevToolItem(id: "toml_to_json", title: "TOML to JSON", category: .formatConverters,
                    summary: "Converts TOML to JSON.", iconName: "arrow.left.arrow.right"),
        DevToolItem(id: "csv_to_json", title: "CSV to JSON", category: .formatConverters,
                    summary: "Parses CSV strings to JSON.", iconName: "tablecells"),
        DevToolItem(id: "csv_parser", title: "CSV Parser & Validator", category: .formatConverters,
                    summary: "Validates CSV alignment.", iconName: "tablecells.badge.ellipsis"),
        DevToolItem(id: "xml_to_json", title: "XML to JSON", category: .formatConverters,
                    summary: "Converts XML DOM to JSON.", iconName: "chevron.left.forwardslash.chevron.right"),
        DevToolItem(id: "xml_formatter", title: "XML Formatter", category: .formatConverters,
                    summary: "Pretty-prints XML documents.", iconName: "text.alignleft"),
        DevToolItem(id: "sql_formatter", title: "SQL Formatter", category: .formatConverters,
                    summary: "Normalizes SQL query indentation.", iconName: "cylinder.split.1x2"),
        DevToolItem(id: "base64_converter", title: "Base64 Encoder/Decoder", category: .formatConverters,
                    summary: "Encodes and decodes Base64 text.", iconName: "lock.shield"),
        DevToolItem(id: "base64_file_converter", title: "Base64 File Converter", category: .formatConverters,
                    summary: "Encodes files to Base64.", iconName: "doc.zipper"),
        DevToolItem(id: "base64_image_decoder", title: "Base64 Image Decoder", category: .formatConverters,
                    summary: "Decodes and previews Base64 images.", iconName: "photo"),
        DevToolItem(id: "base32_converter", title: "Base32 Converter", category: .formatConverters,
                    summary: "RFC 4648 Base32 encoder/decoder.", iconName: "number"),
        DevToolItem(id: "binary_converter", title: "Radix Number Converter", category: .formatConverters,
                    summary: "Binary, octal, hex, decimal.", iconName: "numbers"),
        DevToolItem(id: "binary_hex_converter", title: "Binary to Hex", category: .formatConverters,
                    summary: "Converts bitstreams to hex.", iconName: "number.square"),
        DevToolItem(id: "hex_decimal_converter", title: "Hex Decimal Converter", category: .formatConverters,
                    summary: "Fast hex to decimal calculator.", iconName: "number"),
        DevToolItem(id: "ascii_hex_converter", title: "ASCII Hex Converter", category: .formatConverters,
                    summary: "Converts ASCII text to hex bytes.", iconName: "character.textbox"),
        DevToolItem(id: "epoch_converter", title: "Unix Epoch Converter", category: .formatConverters,
                    summary: "Converts timestamps to dates.", iconName: "clock"),

        // Category 3: Cryptography & Security (15 Tools)
        DevToolItem(id: "aes_encryption", title: "AES Encryption Tool", category: .cryptography,
                    summary: "AES-128/256 CBC/GCM cipher.", iconName: "key.fill"),
        DevToolItem(id: "rsa_key_generator", title: "RSA Key Generator", category: .cryptography,
                    summary: "Generates RSA PEM keypairs.", iconName: "key.horizontal"),
        DevToolItem(id: "hash_generator", title: "Cryptographic Hashes", category: .cryptography,
                    summary: "MD5, SHA1, SHA256, SHA512 digests.", iconName: "number.circle.fill"),
        DevToolItem(id: "hmac_generator", title: "HMAC Generator", category: .cryptography,
                    summary: "Computes HMAC signatures.", iconName: "signature"),
        DevToolItem(id: "bcrypt_hash_generator", title: "Bcrypt Hash Generator", category: .cryptography,
                    summary: "Generates Bcrypt password hashes.", iconName: "lock.rotation"),
        DevToolItem(id: "jwt_decoder", title: "JWT Token Decoder", category: .cryptography,
                    summary: "Inspects claims and expiration.", iconName: "doc.badge.gearshape"),
        DevToolItem(id: "password_generator", title: "Secure Password Gen", category: .cryptography,
                    summary: "Generates random secure passwords.", iconName: "asterisk"),
        DevToolItem(id: "password_strength_meter", title: "Password Entropy Meter", category: .cryptography,
                    summary: "Calculates entropy and crack time.", iconName: "gauge.with.needle"),
        DevToolItem(id: "csrf_token_generator", title: "CSRF Token Generator", category: .cryptography,
                    summary: "Cryptographic anti-CSRF tokens.", iconName: "shield.lefthalf.filled"),
        DevToolItem(id: "certificate_decoder", title: "X.509 Certificate Decoder", category: .cryptography,
                    summary: "Decodes SSL/TLS certificates.", iconName: "checkmark.seal"),
        DevToolItem(id: "ssl_checker", title: "SSL / TLS Handshake Audit", category: .cryptography,
                    summary: "Audits host cipher suites.", iconName: "network.badge.shield.half.filled"),
        DevToolItem(id: "app_receipt_inspector", title: "App Receipt Inspector", category: .cryptography,
                    summary: "Validates PKCS #7 receipts.", iconName: "receipt"),
        DevToolItem(id: "biometric_auth_sim", title: "Biometric Auth Simulator", category: .cryptography,
                    summary: "Simulates Face ID / Touch ID.", iconName: "touchid"),
        DevToolItem(id: "multi_cipher_workspace", title: "Multi-Cipher Workspace", category: .cryptography,
                    summary: "ChaCha20, 3DES ciphers.", iconName: "shield"),
        DevToolItem(id: "unix_permissions_calculator", title: "Unix Chmod Calculator", category: .cryptography,
                    summary: "Octal to symbolic permissions.", iconName: "terminal.fill"),

        // Category 4: Text & String Utilities (16 Tools)
        DevToolItem(id: "case_converter", title: "Letter Case Converter", category: .textUtilities,
                    summary: "camelCase, snake_case, Pascal.", iconName: "textformat"),
        DevToolItem(id: "text_case_swapper", title: "Case Inversion Swapper", category: .textUtilities,
                    summary: "Inverts character casing.", iconName: "arrow.up.and.down.textformat"),
        DevToolItem(id: "character_escaper", title: "Code Character Escaper", category: .textUtilities,
                    summary: "Escapes strings for languages.", iconName: "character.cursor.ibeam"),
        DevToolItem(id: "json_string_escaper", title: "JSON String Escaper", category: .textUtilities,
                    summary: "Escapes quotes and control chars.", iconName: "quote.opening"),
        DevToolItem(id: "string_escaper", title: "Generic String Escaper", category: .textUtilities,
                    summary: "Custom delimiter escaping.", iconName: "pencil.line"),
        DevToolItem(id: "string_length_counter", title: "Character & Word Counter", category: .textUtilities,
                    summary: "Counts words, lines, and bytes.", iconName: "number"),
        DevToolItem(id: "text_counter", title: "Text Readability Analyzer", category: .textUtilities,
                    summary: "Flesch-Kincaid grade analysis.", iconName: "chart.bar.doc.horizontal"),
        DevToolItem(id: "text_deduplicator", title: "Line Deduplicator", category: .textUtilities,
                    summary: "Strips duplicate lines.", iconName: "line.3.horizontal.decrease"),
        DevToolItem(id: "text_line_remover", title: "Empty Line Remover", category: .textUtilities,
                    summary: "Cleans empty whitespace lines.", iconName: "trash"),
        DevToolItem(id: "lorem_ipsum_generator", title: "Lorem Ipsum Generator", category: .textUtilities,
                    summary: "Generates placeholder paragraphs.", iconName: "text.alignleft"),
        DevToolItem(id: "uuid_generator", title: "UUID v4 / v5 Generator", category: .textUtilities,
                    summary: "Generates unique identifiers.", iconName: "number.circle"),
        DevToolItem(id: "random_string_generator", title: "Random String Generator", category: .textUtilities,
                    summary: "Generates alphanumeric strings.", iconName: "die.face.5"),
        DevToolItem(id: "barcode_generator", title: "Barcode Image Generator", category: .textUtilities,
                    summary: "Code-128 and EAN barcodes.", iconName: "barcode"),
        DevToolItem(id: "ascii_art_generator", title: "ASCII Art Banner Maker", category: .textUtilities,
                    summary: "Converts text to ASCII art.", iconName: "paintpalette"),
        DevToolItem(id: "html_entity_converter", title: "HTML Entity Encoder", category: .textUtilities,
                    summary: "Encodes characters to HTML.", iconName: "chevron.left.forwardslash.chevron.right"),
        DevToolItem(id: "url_slug_generator", title: "URL Slug Sanitizer", category: .textUtilities,
                    summary: "Converts titles to clean slugs.", iconName: "link")
    ]
}
