//
//  DevToolsCatalogPart3.swift
//  CodeEdit
//
//

import Foundation

/// Catalog partition 3: Tools for Categories 9 through 11 (49 Tools).
public struct DevToolsCatalogPart3: Sendable {
    public static let tools: [DevToolItem] = [
        // Category 9: System, Hardware & OS Utilities (14 Tools)
        DevToolItem(id: "cpu_monitor", title: "Real-time CPU Monitor", category: .systemHardware,
                    summary: "CPU core utilization graphs.", iconName: "cpu"),
        DevToolItem(id: "fps_monitor", title: "UI Frame Rate Monitor", category: .systemHardware,
                    summary: "Measures rendering FPS drops.", iconName: "speedometer"),
        DevToolItem(id: "energy_impact_monitor", title: "Energy Impact Monitor", category: .systemHardware,
                    summary: "Battery drain metrics.", iconName: "bolt.fill"),
        DevToolItem(id: "battery_status", title: "Battery Health Inspector", category: .systemHardware,
                    summary: "Cycle count and thermals.", iconName: "battery.100"),
        DevToolItem(id: "disk_usage_analyzer", title: "Disk Footprint Analyzer", category: .systemHardware,
                    summary: "Workspace storage by type.", iconName: "internaldrive"),
        DevToolItem(id: "device_info", title: "System & Hardware Info", category: .systemHardware,
                    summary: "Kernel, CPU, GPU cores, RAM.", iconName: "laptopcomputer"),
        DevToolItem(id: "env_var_inspector", title: "Environment Var Inspector", category: .systemHardware,
                    summary: "Process environment variables.", iconName: "list.bullet.rectangle"),
        DevToolItem(id: "clipboard_inspector", title: "Clipboard Flavor Inspector", category: .systemHardware,
                    summary: "Inspects pasteboard types.", iconName: "doc.on.clipboard"),
        DevToolItem(id: "app_sandbox_explorer", title: "App Sandbox Explorer", category: .systemHardware,
                    summary: "Container directory explorer.", iconName: "shippingbox"),
        DevToolItem(id: "app_state_inspector", title: "State Store Inspector", category: .systemHardware,
                    summary: "Live notification observers.", iconName: "eye"),
        DevToolItem(id: "cache_viewer", title: "Cache Storage Manager", category: .systemHardware,
                    summary: "In-memory and disk caches.", iconName: "externaldrive"),
        DevToolItem(id: "bundle_size_analyzer", title: "App Bundle Size Analyzer", category: .systemHardware,
                    summary: "Resource asset breakdown.", iconName: "chart.pie"),
        DevToolItem(id: "deep_link_tester", title: "Deep Link URL Tester", category: .systemHardware,
                    summary: "Universal Links and schemes.", iconName: "link.badge.plus"),
        DevToolItem(id: "mac_address_generator", title: "MAC Address Generator", category: .systemHardware,
                    summary: "Unicast and multicast MACs.", iconName: "network"),

        // Category 10: Developer Cheatsheets & Reference Guides (16 Tools)
        DevToolItem(id: "swift_language_reference", title: "Swift Language Reference", category: .cheatsheets,
                    summary: "Macros, generics, concurrency.", iconName: "swift"),
        DevToolItem(id: "swift_concurrency_guide", title: "Swift Concurrency Guide", category: .cheatsheets,
                    summary: "Async/await, TaskGroups, actors.", iconName: "arrow.triangle.merge"),
        DevToolItem(id: "swiftui_performance", title: "SwiftUI Performance Guide", category: .cheatsheets,
                    summary: "View invalidation and identity.", iconName: "bolt"),
        DevToolItem(id: "git_cheatsheet", title: "Git Command Cheatsheet", category: .cheatsheets,
                    summary: "Recovery and cherry-picking.", iconName: "arrow.triangle.branch"),
        DevToolItem(id: "git_branching_strategies", title: "Git Branching Strategies", category: .cheatsheets,
                    summary: "GitFlow vs Trunk-based.", iconName: "point.topleft.down.curvedto.point.bottomright.up"),
        DevToolItem(id: "lldb_cheatsheet", title: "LLDB Debugger Cheatsheet", category: .cheatsheets,
                    summary: "Breakpoints and expressions.", iconName: "ladybug"),
        DevToolItem(id: "swiftlint_config_guide", title: "SwiftLint Configuration Guide", category: .cheatsheets,
                    summary: "Rule sets and disable directives.", iconName: "doc.text.magnifyingglass"),
        DevToolItem(id: "app_store_guidelines", title: "App Store Review Guidelines", category: .cheatsheets,
                    summary: "Rejection causes summary.", iconName: "applelogo"),
        DevToolItem(id: "apple_silicon_guide", title: "Apple Silicon Optimization", category: .cheatsheets,
                    summary: "NEON, Accelerate, Neural Engine.", iconName: "cpu.fill"),
        DevToolItem(id: "ios_screen_resolutions", title: "Apple Device Dimensions", category: .cheatsheets,
                    summary: "Points, pixels, safe areas.", iconName: "ipad"),
        DevToolItem(id: "xcode_shortcuts_guide", title: "Xcode Shortcuts Cheatsheet", category: .cheatsheets,
                    summary: "Default keyboard commands.", iconName: "command"),
        DevToolItem(id: "markdown_syntax_guide", title: "Markdown Syntax Guide", category: .cheatsheets,
                    summary: "GFM tables, alerts, blocks.", iconName: "doc.richtext"),
        DevToolItem(id: "semver_checker", title: "SemVer Version Comparator", category: .cheatsheets,
                    summary: "Semantic Version precedence.", iconName: "tag"),
        DevToolItem(id: "timestamp_converter", title: "Timezone Timestamp Converter", category: .cheatsheets,
                    summary: "International timezones.", iconName: "globe.americas"),
        DevToolItem(id: "timezone_calculator", title: "Timezone Offset Calculator", category: .cheatsheets,
                    summary: "Daylight saving time offsets.", iconName: "sun.max"),
        DevToolItem(id: "date_formatter_playground", title: "DateFormatter Playground", category: .cheatsheets,
                    summary: "Format strings testbed.", iconName: "calendar.badge.clock"),

        // Category 11: Units, Measurements & Miscellaneous (19 Tools)
        DevToolItem(id: "length_converter", title: "Length Unit Converter", category: .unitsMeasurement,
                    summary: "Meters, feet, inches, nautical.", iconName: "ruler"),
        DevToolItem(id: "weight_converter", title: "Weight Unit Converter", category: .unitsMeasurement,
                    summary: "Kilograms, pounds, ounces.", iconName: "scalemass"),
        DevToolItem(id: "temperature_converter", title: "Temperature Converter", category: .unitsMeasurement,
                    summary: "Celsius, Fahrenheit, Kelvin.", iconName: "thermometer"),
        DevToolItem(id: "percentage_calculator", title: "Percentage Calculator", category: .unitsMeasurement,
                    summary: "Calculates changes and markups.", iconName: "percent"),
        DevToolItem(id: "mime_type_lookup", title: "MIME Type Directory", category: .unitsMeasurement,
                    summary: "MIME types and extensions.", iconName: "doc.circle"),
        DevToolItem(id: "diff_checker", title: "Visual Text Diff Checker", category: .unitsMeasurement,
                    summary: "Side-by-side text diffing.", iconName: "doc.badge.plus"),
        DevToolItem(id: "markdown_previewer", title: "Markdown Previewer", category: .unitsMeasurement,
                    summary: "Markdown with live HTML tab.", iconName: "doc.richtext"),
        DevToolItem(id: "breakpoint_manager", title: "Breakpoint Manager", category: .unitsMeasurement,
                    summary: "Central active breakpoints.", iconName: "circle.fill"),
        DevToolItem(id: "designer_scratchpad", title: "Designer Scratchpad", category: .unitsMeasurement,
                    summary: "Color combos and typography.", iconName: "paintpalette.fill"),
        DevToolItem(id: "devtools_main_launcher", title: "DevTools Launcher", category: .unitsMeasurement,
                    summary: "Searchable launcher dashboard.", iconName: "square.grid.3x3.fill"),
        DevToolItem(id: "expanded_devtools", title: "Expanded DevTools Grid", category: .unitsMeasurement,
                    summary: "Category grid for discovery.", iconName: "square.grid.2x2.fill"),
        DevToolItem(id: "app_icon_switcher", title: "App Icon Selector", category: .unitsMeasurement,
                    summary: "Interactive app icon switcher.", iconName: "app.gift"),
        DevToolItem(id: "app_icon_manager", title: "App Icon Dynamic Manager", category: .unitsMeasurement,
                    summary: "Dynamic app icon replacement.", iconName: "app.badge"),
        DevToolItem(id: "icon_preview_generator", title: "App Icon Preview Gen", category: .unitsMeasurement,
                    summary: "Generates standard icon sizes.", iconName: "app.dashed"),
        DevToolItem(id: "credits_licenses", title: "Credits & Licenses", category: .unitsMeasurement,
                    summary: "Software licenses attribution.", iconName: "heart.text.square"),
        DevToolItem(id: "project_inspector", title: "Project Metrics Inspector", category: .unitsMeasurement,
                    summary: "Files, lines of code, graphs.", iconName: "chart.pie.fill"),
        DevToolItem(id: "localization_manager", title: "String Catalog Manager", category: .unitsMeasurement,
                    summary: "Visual string catalog editor.", iconName: "globe.badge.chevron.backward"),
        DevToolItem(id: "embedded_terminal", title: "Embedded Terminal", category: .unitsMeasurement,
                    summary: "Executes shell commands in IDE.", iconName: "terminal"),
        DevToolItem(id: "code_dictionary_search", title: "Coding Dictionary Search", category: .unitsMeasurement,
                    summary: "Interactive dictionary search.", iconName: "book.fill")
    ]
}
